#!/bin/bash
BUILD=../.build
rm -rf $BUILD
cp -r . $BUILD

# Remove unwanted files
remove=(
  .gitignore
  README.md
  build
  .git
)
for file in "${remove[@]}"; do
  rm -rf $BUILD/$file
done

# Convert PHP pages to static HTML
pushd $BUILD > /dev/null
files=( $(find . | grep *index.php) )
for file in "${files[@]}"; do
  pushd "$(dirname $file)" > /dev/null
  php index.php > index.html
  rm -f index.php
  popd > /dev/null
done
rm -rf components

# Push with git
git init
git remote add origin https://github.com/farhananshah/edhaus.git
git add .
git commit -m "Update on $(date)"
git push -f origin master:gh-pages
popd > /dev/null
mv $BUILD .
