#!/bin/bash
rm -rf .build
wget -r http://localhost:2017 > /dev/null 2>&1
if [ "$?" -ne "0" ]; then
  echo "Please turn on a server"
  exit 1
fi
mv localhost:2017 .build
pages=(
  testimonials
  publications
  podcasts
  services
  clients
  contact
  blogs
  team
)
for page in "${pages[@]}"; do
  mv .build/$page .build/tmp
  mkdir .build/$page
  mv .build/tmp .build/$page/index.html
done

pushd .build > /dev/null
git init
git remote add origin https://github.com/farhananshah/edhaus.git
git add .
git commit -m "Update on $(date)"
git push -f origin master:gh-pages
popd > /dev/null
